/*
 * Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.movieplex8.rest;

import java.util.Set;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

/**
 * @author Arun Gupta
 */
@ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(org.glassfish.movieplex8.json.MovieReader.class);
        resources.add(org.glassfish.movieplex8.json.MovieWriter.class);
        resources.add(org.glassfish.movieplex8.rest.MovieFacadeREST.class);
        resources.add(org.glassfish.movieplex8.rest.SalesFacadeREST.class);
        resources.add(org.glassfish.movieplex8.rest.ShowTimingFacadeREST.class);
        resources.add(org.glassfish.movieplex8.rest.TheaterFacadeREST.class);
        resources.add(org.glassfish.movieplex8.rest.TimeslotFacadeREST.class);
    }

//    @Override
//    public Set<Class<?>> getClasses() {
//        return getRestResourceClasses();
//    }

//    /**
//     * Do not modify this method. It is automatically generated by NetBeans REST support.
//     */
//    private Set<Class<?>> getRestResourceClasses() {
//        Set<Class<?>> resources = new java.util.HashSet<>();
//        resources.add(org.glassfish.movieplex7.MovieSessionBean.class);
//        try {
//            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
//            resources.add(jacksonProvider);
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        return resources;
//    }
    
}
